### ISSUE TITLE
OmpSs-2 job launched on SLURM

### ISSUE THREAD

**Issue by Z10Frank** [bsc-pm/nanos6#10]
I am launching my taskified code on a cluster with SLURM, but I don't see a sensitive reduction of the time spent on the parallelized part increasing the `cpus-per-task`. The physical results on my benchmark seem to be the same, so it's only a problem of efficient parallelization.

I have used the same taskification strategy used with other task programming systems (OpenMP task, Eventify), so from those tests I know that normally the execution time should decrease with the number of CPU cores in my benchmark. With OpenMP I have to set also the environment variable for the number of threads; with Eventify it is sufficient to increase the `cpus-per-task` in the submission script. So I am wondering if I am missing something in my submission script for the job. Is there a minimal test I can run to check the scaling of the execution time with my installation, environment, cluster?

My submission script:
```
#!/bin/bash
#SBATCH --job-name=smileiompss
#SBATCH --output=smilei.log
#SBATCH --time=01:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --partition=cpu_short

# Clean and to Load the same modules at the compilation phases
module purge

module load zlib/1.2.9/gcc-9.2.0
module load anaconda2/2019.10/gcc-9.2.0
module load gcc/11.2.0/gcc-4.8.5 
module load hdf5/1.10.7/gcc-9.2.0-openmpi
module load openmpi/4.0.2/gcc-9.2.0

export INSTALLATION_PREFIX_NANOS6=/gpfs/users/massimof/nanos6/install

export HDF5_ROOT_DIR=/gpfs/softs/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/hdf5-1.10.7-j6enx3ruksp5mjo5ed6lhywrzozihamq

export LD_LIBRARY_PATH=/gpfs/workdir/massimof/llvm-github-release-2021.11/llvm/install/lib:$LD_LIBRARY_PATH

export I_MPI_CXX=/gpfs/workdir/massimof/llvm-github-release-2021.11/llvm/install/bin/clang++ 
export OMPI_CXX=/gpfs/workdir/massimof/llvm-github-release-2021.11/llvm/install/bin/clang++

# echo of commands
set -x

# To compute in the submission directory
cd ${SLURM_SUBMIT_DIR}

# execution 
srun ./smilei tst2d_02_radiation_pressure_acc.py
```

**Comment by kevinsala** [comment]
Hi Francesco,
Depending on the SLURM configuration, the `srun` may need an extra option in order to set the correct CPU binding to the launched commands (i.e. `./smilei`). Could you try adding the option `--cpu_bind=cores`?

The full command would be:
```
srun --cpu_bind=cores ./smilei tst2d_02_radiation_pressure_acc.py
```

If you don't see any difference, please attach the output of the following command so that we can get more information:

```
srun --cpu_bind=cores nanos6-info --runtime-details
```

As a test, you can execute that command from the same jobscript. The `nanos6-info` command should be installed in `$INSTALLATION_PREFIX_NANOS6/bin`, so you will need this path in the `$PATH` envar. The command will provide some information about the CPU binding, versions, etc. and will help us detecting if something is wrong.

**Comment by Z10Frank** [comment]
Hello, 
thank you, no visible difference was observed, so following is the output of the command with `nanos6-info`.
Is anything wrong?
```
Runtime path /gpfs/users/massimof/nanos6/install/lib/libnanos6-optimized-discrete.so.0.0.0
Runtime Version 2.7 2021-11-16 16:28:01 +0000 91468123
Runtime Branch master
Runtime Compiler Version g++ (Spack GCC) 9.2.0
Runtime Compiler Flags -DNDEBUG -Wall -Wextra -Wdisabled-optimization -Wshadow -fvisibility=hidden -O3 -flto
Per-process CPU limit, in seconds unlimited seconds
Largest file that can be created, in bytes unlimited bytes
Maximum size of data segment, in bytes unlimited bytes
Maximum size of stack segment, in bytes unlimited bytes
Largest core file that can be created, in bytes 0 bytes
Largest resident set size, in bytes. This affects swapping; processes that are exceeding their resident set size will be more likely to have physical memory taken from them 85899345920 bytes
Number of open files 8192
Address space limit unlimited
Number of processes 4096 processes
Locked-in-memory address space unlimited
Maximum number of file locks unlimited file locks
Maximum number of pending signals 771079 signals
Maximum bytes in POSIX message queues 819200 bytes
Maximum nice priority allowed to raise to. Nice levels 19 .. -20 correspond to 0 .. 39 values of this resource limit 0
Maximum realtime priority allowed for non-priviledged processes 0
Maximum CPU time in µs that a process scheduled under a real-time scheduling policy may consume without making a blocking system call before being forcibly descheduled unlimited µs
Initial CPU List 0-1,7-24
NUMA Node 0 CPU List 0-1,7-19
NUMA Node 1 CPU List 20-24
SchedulingPolicy fifo
Scheduler LocalScheduler
Dependency Implementation discrete
Threading Model pthreads
Stack Size 8388608
```

Job script launching the command:
```
#!/bin/bash
#SBATCH --job-name=mpi_openmp
#SBATCH --output=smilei.log
#SBATCH --time=01:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --nodes=1
#SBATCH --partition=cpu_short
# available partitions: cpu_short|cpu_med|cpu_prod|cpu_long

module purge
module load zlib/1.2.9/gcc-9.2.0
module load gcc/11.2.0/gcc-4.8.5

export INSTALLATION_PREFIX_NANOS6=/gpfs/users/massimof/nanos6/install
export LD_LIBRARY_PATH=/gpfs/workdir/massimof/llvm-github-release-2021.11/llvm/install/lib:$LD_LIBRARY_PATH

# echo of commands
set -x

# To compute in the submission directory
cd ${SLURM_SUBMIT_DIR}

srun --cpu_bind=cores $INSTALLATION_PREFIX_NANOS6/bin/nanos6-info --runtime-details


```

**Comment by kevinsala** [comment]
Hi Francesco,
From the command's output, it seems that the application is able to use the 20 CPUs correctly. The runtime system leverages the CPUs 0-1,7-24 (i.e., `Initial CPU List 0-1,7-24`), so 20 in total. However, this configuration could produce performance problems because you use two NUMA nodes. The CPUs 0-1,7-19 (15 total) are in the NUMA 0, while there are other 5 CPUs in the NUMA 1.

Usually, running an HPC application in multiple NUMA nodes can damage the performance. Depending on the initialization of the application's data, most of this data could reside in a single NUMA node. For instance, with the default first-touch NUMA policy, the CPU that first touches a data's memory page (on page fault) causes that page to be allocated in the corresponding node of that CPU. Thus, if the initialization of the app data is done sequentially from the same CPU (e.g., by the `main` task), all those pages will reside in the same NUMA node, and the CPUs from other NUMA nodes will have an extra penalty when accessing those pages.

Additionally, having an unbalanced number of CPUs in each NUMA can also degrade the performance.

The first step I would do is repeat the experiment but making sure that all CPUs are in the same NUMA node, to see if it's related to this issue or not. Another aspect to check is whether this machine has hyper-threading or SMT enabled. In most cases, hyper-threading is not beneficial in HPC applications, so it's better to use one single hardware thread per core.

**Comment by Z10Frank** [comment]
Thank you! I think I have found a problem: inside the interval measured by my timer there was a part not parallelized causing a bottleneck, I'll parallelize it and check the scaling to see if everything works as expected.
